language: elixir
notifications:
  recipients:
    - klaus.alfert@googlemail.com
otp_release:
  - 17.4
env:
  ELIXIR=v1.0.2
before_script:
  - mix local.hex --force
  - mix local.rebar
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover --exclude performance:true"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report